version: "3.8"

services:
  portfolix:
    container_name: portfolix
    image: docker.pkg.github.com/mervin16/portfolix/portfolix:1.2.1
    build: ./
    env_file:
      - config_local.env
    expose:
      - 8084
    restart: always
    networks:
      - portfolix_net

networks:
  portfolix_net:
    name: portfolix_network
    driver: bridge
