version: "3.8"

services:
  portfolix:
    container_name: portfolix
    image: mervin16/portfolix:dev
    build: ./
    env_file:
      - config_local.env
    expose:
      - 8086
    restart: always
    networks:
      - portfolix_net

  nginx2:
    build: ./nginx
    container_name: nginx2
    ports:
      - "8086:80"
    restart: always
    networks:
      - portfolix_net

networks:
  portfolix_net:
    name: portfolix_network
    driver: bridge
